"""empty message

Revision ID: 050073241314
Revises: e198b4e8c30d
Create Date: 2023-01-29 01:09:36.304054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050073241314'
down_revision = 'e198b4e8c30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robbery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeout', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robbery', schema=None) as batch_op:
        batch_op.drop_column('timeout')

    # ### end Alembic commands ###
