"""empty message

Revision ID: 1e0e9892f759
Revises: 
Create Date: 2023-01-28 04:48:42.936290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0e9892f759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robbery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_damage', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_damage', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robbery', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('max_damage')
        batch_op.drop_column('min_damage')

    # ### end Alembic commands ###
