"""empty message

Revision ID: b28d58ec4299
Revises: 1e0e9892f759
Create Date: 2023-01-28 04:51:45.596866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28d58ec4299'
down_revision = '1e0e9892f759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robbery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_damage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_damage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))
        batch_op.alter_column('min_exp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_exp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('min_cash',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_cash',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('level_required',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('robbery', schema=None) as batch_op:
        batch_op.alter_column('level_required',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_cash',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('min_cash',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_exp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('min_exp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('difficulty')
        batch_op.drop_column('max_damage')
        batch_op.drop_column('min_damage')

    # ### end Alembic commands ###
